
- hosts: all
  tasks:
  - name: yum install
    yum:
      name: "{{ item }}"
      state: present
    with_items:
      - git
      - http://rpms.remirepo.net/enterprise/remi-release-7.rpm

  - name: install php
    yum:
      name: "{{ item }}"
      enablerepo: remi,remi-php72
      state: present
    with_items:
      - php

  - name: get composer
    get_url:
      url: https://getcomposer.org/installer
      dest: /tmp/composer-setup.php

  - name: install composer
    shell: chdir=/tmp php composer-setup.php

  - name: move composer.phar
    shell: mv /tmp/composer.phar /bin/composer

